name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: pytest

    - name: Deploy to Server
      env:
        HOST: ${{ secrets.SERVER_HOST }}
        USER: ${{ secrets.SERVER_USER }}
        SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
      run: |
        # Write the SSH private key to a file
        echo "${SSH_KEY}" > ssh_key
        chmod 600 ssh_key

        # Define deployment path
        DEPLOY_PATH="/path/to/deployment/directory"

        # Copy code to server
        scp -i ssh_key -o StrictHostKeyChecking=no -r . ${USER}@${HOST}:${DEPLOY_PATH}

        # SSH into server and deploy
        ssh -i ssh_key -o StrictHostKeyChecking=no ${USER}@${HOST} << EOF
          cd ${DEPLOY_PATH}
          python3 -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

          # Kill any running uvicorn process on port 8000
          fuser -k 8000/tcp || true

          # Run FastAPI (you may want to set up systemd or supervisor instead of nohup)
          nohup venv/bin/uvicorn app.main:app --host 0.0.0.0 --port 8000 &
        EOF

        # Clean up SSH key
        rm ssh_key
