name: Deploy Backend

on:
  push:
    branches:
      - Production_Backend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: pytest

    - name: Deploy to Server
      env:
        HOST: ${{ secrets.SERVER_HOST }}
        USER: ${{ secrets.SERVER_USER }}
        SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
      run: |
        # Write SSH private key to file
        echo "${SSH_KEY}" > ssh_key
        chmod 600 ssh_key

        # Define deployment path
        DEPLOY_PATH="/SEM4/Financial Adivisor/Backend"

        # Sync only the code (skip virtual env, .git, __pycache__, etc.)
        rsync -avz -e "ssh -i ssh_key -o StrictHostKeyChecking=no" \
          --exclude '.venv' --exclude 'venv' --exclude '.git' --exclude '__pycache__' \
          ./ ${USER}@${HOST}:${DEPLOY_PATH}

        # SSH and deploy
        ssh -i ssh_key -o StrictHostKeyChecking=no ${USER}@${HOST} << 'EOF'
          set -e
          cd /SEM4/Financial\ Adivisor/Backend
          python3 -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

          # Kill any process using port 8000
          fuser -k 8000/tcp || true

          # Run app with nohup (fix path)
          nohup .venv/bin/uvicorn app.main:app --host 0.0.0.0 --port 8000 &
        EOF

        # Clean up SSH key
        rm ssh_key
